FROM node:22-alpine

WORKDIR /client

RUN apk add --no-cache git

# zuerst nur package-Dateien (Cache!)
COPY package.json package-lock.json* ./
RUN npm install

# 🔥 DAS HAT GEFEHLT
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
