
services:
  client:
    build:
      context: ./client
      dockerfile: "Dockerfile.dev"
    working_dir: /client/
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: npm run dev --host

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - .:/workspace
    env_file:
      - ./server/.env
    ports:
      - 5000:5000
    command: /bin/bash -c "cd /home/studyplanner-server/server/ && python3 load.py && python3 app.py"
    depends_on:
      - mongo

  # MongoDB-Datenbank
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    hostname: "mongo-server"

volumes:
  mongo_data:
